apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-deploy
  template:
    metadata:
      labels:
        app: user-deploy
    spec:
      containers:
        - name: user-deploy
          image: 762921032637.dkr.ecr.ap-northeast-2.amazonaws.com/user:f18a009
          ports:
            - containerPort: 8080